/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:7d3700da-1cdb-4f8a-a819-c8b0967147e2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_BX2nJvAps",
    "aws_user_pools_web_client_id": "602hp1nscamsff4di0cpveqkqm",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://uaa2wtt5mndglgioy2fxbnfhee.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-6txu7p3tovhk5bm2dg5e3woctm",
    "aws_user_files_s3_bucket": "reactwebf560df886e774f758fd46f70a3ca3c6770212-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
